In [ ]:

#stemming is a process of reducing inflection in words to their root form such as mapping a group of words to the same stem even if the stem itself is not a valid word in the anguage.

In [ ]:
Ques 1:- create dataset -> do text-processing -> multi-class classification ->movie data  ->name,discription,jenre

In [ ]:
what is featured extraction from text?--->ML--> input feature is to be given (garbage in garbage out)
acqisition->preprocessing-->text vectorisation-->algorithm

Corpus,vocabulary,document,word
One hot coding->problems:
sparse array(many 0 in array+overfeeding)
out of vocabulary(oov)
no fixed size
no capturing of semantic meaning

bag of words:  people watch campusx write  comment(kitni baar aaye hain(order doesnot matter, context doesnot matter))
people watch campusx[1,1,1,0,0]
campusx watch campusx[0,1,2,0,0]
people write comment[1,0,0,1,1]
campusx write comment[0,0,1,1,1]
n dimension mein vectoor ko dikhao angle less->similar 

In [28]:
import pandas as pd
import numpy as np

In [32]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
bow=cv.fit_transform(df['text'])
print(cv.vocabulary_)
print(bow[0].toarray())
print(bow[2].toarray())

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}
[[1 0 1 1 0]]
[[0 1 1 0 1]]


In [42]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()#out of vocabulary problem does not exist

array([[2, 1, 0, 1, 1]], dtype=int64)

In [ ]:
max-feature
disadvantages of bag of words:(spasity,oov,not considering order,bag of word "this book is good" or "this book is not good" ko ek jaisa hi samjhega angle less hoga
and hence meaning bhi ek hi manega------>USE NGRAMS
    N-grams----> Bag of n-grams->bow

In [52]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()#out of vocabulary problem does not exist
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))
bow=cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [58]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()#out of vocabulary problem does not exist
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,3))
bow=cv.fit_transform(df['text'])
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}
15


In [ ]:
#benifits of N-grams ---> able to capture semantic of the sentence  2. easy to implemrnt
#disadvatages of N-grams-->Dimention increases  2. slow down algo   3. ignore new words

In [ ]:
# agar ek word ek paticular document(line) mein jyada aa rha hai pr baki corpus mein nhi aa rha hai --> to uss word ko jyada priority denge
#tf=gives different values to different words
#TF(t,d)=number of occurrences of term t in document d/total number of term in the document d
##IDF(t)=Total number of documents in the corpus/nnumber of documents wth the term t in them
#term rare(IDF high)   term frequent (IDF low)
#koi bhi term kitna frequent hai kisi bhi document mein* term kitna rare hai poore corpus mein
# TF*IDF

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 3526: character maps to <undefined>

In [ ]:
import spacy
spacy.cli.download("en_core_web_sm")
nlp=spacy.load('en_core_web_sm')
with open("Top_rated.txt","r") as file:
    text=file.read()
doc=nlp(text)
print("Tokens:")
for token in doc:
    print(token.text)